### PR TITLE
Checklist: Allow uppercase 'X' to be used

### PR DESCRIPTION
**Pull request by vHanda**

### CODE REVIEW

**Comment by tomyeh** [comment]
Accepted but I'll remove the code setting an extra attribute.

**Comment by vHanda** [comment]
I need the extra attribute, as I'm trying to convert the AST back to the original markdown without any changes.

**Comment by tomyeh** [comment]
I don't think the uppercase attribute helps much here. If the user uses `[X]`, you can parse it back straightforward when converting to `[ ]`. On the other hand, if the original content is `[ ]`, there is no info there.

**Comment by vHanda** [comment]
I'm sorry. I don't quite follow.

If I have Element with tag 'input' and attribute 'type: checkbox', and 'checked'. The appropriate markdown could be either `[X]` or `[x]`, without the 'uppercase' attribute, how can I figure out which of the two should be used?

I don't see any way of getting the raw text which was used to generate the AST's Element.

Could you please elaborate?

**Comment by tomyeh** [comment]
My bad. I assumed you're implementing the toggling feature: allow users clicking the checkbox to change the original markdown.

Regarding generating the markdown based on AST, it's not in the goal of my fork. You probably need to fork again. Just curious, why you need to do that? You're supposed to have the original markdown.

**Comment by vHanda** [comment]
I have an application which allows users to view/edit markdown files in various different ways. One of the views is a task list.

For that, I parse the markdown and render only the parts of the AST that I'm interested in. The user can then add/remove/modify items, and the AST is accordingly modified. At the end this needs to saved back in a file in markdown.

I'm trying to implement a Markdown Renderer like the HTML one, except that the Markdown produced should be identical to the original one.

My app is a Markdown editor + git integrated, so if the markdown is changed in anyway, the diff is clearly visible.

**Comment by tomyeh** [comment]
Cool!

**Pull request merged**
